// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

contract EnvironmentContract {
    function tailorList() public returns (string[] memory) {}

    function allowedColorList() public returns (string[] memory) {}
}

/**
 * @title PolicyDecisionPoint1
 * @author
 * @notice Smart Policy, its code is not known at design time and is dynamically generated by the PAP based on an XACML policy
 */
contract PolicyInformationPoint {
    address private admin;
    address private pdp;
    EnvironmentContract private _envContr;

    constructor(address _environmentContract) {
        admin = msg.sender;
        pdp = address(0);
        _envContr = EnvironmentContract(_environmentContract);
    }

    function setPDP(address pdpAddr) public {
        if (msg.sender != admin) {
            revert();
        }

        pdp = pdpAddr;
    }

    function checkSender(address sender) private view {
        if (sender != pdp) {
            revert();
        }
    }

  

    function envAllowedColorList() public returns (string[] memory) {
        checkSender(msg.sender);
        return _envContr.allowedColorList();
    }

    function envTailorList() public returns (string[] memory) {
        checkSender(msg.sender);
        return _envContr.tailorList();
    }
}
